In [44]:
for x in range (2000,3201):
    if (x%7)==0 and (x%5)!=0:
        print(x, end='  '),
        
    

2002  2009  2016  2023  2037  2044  2051  2058  2072  2079  2086  2093  2107  2114  2121  2128  2142  2149  2156  2163  2177  2184  2191  2198  2212  2219  2226  2233  2247  2254  2261  2268  2282  2289  2296  2303  2317  2324  2331  2338  2352  2359  2366  2373  2387  2394  2401  2408  2422  2429  2436  2443  2457  2464  2471  2478  2492  2499  2506  2513  2527  2534  2541  2548  2562  2569  2576  2583  2597  2604  2611  2618  2632  2639  2646  2653  2667  2674  2681  2688  2702  2709  2716  2723  2737  2744  2751  2758  2772  2779  2786  2793  2807  2814  2821  2828  2842  2849  2856  2863  2877  2884  2891  2898  2912  2919  2926  2933  2947  2954  2961  2968  2982  2989  2996  3003  3017  3024  3031  3038  3052  3059  3066  3073  3087  3094  3101  3108  3122  3129  3136  3143  3157  3164  3171  3178  3192  3199  

In [56]:
n=int(input())
k=1
for i in range(1,n+1): 
    k = k * i 
print (k ,end='')

5
120

In [73]:
k=int(input("donner une valeur"))
dict={}
for i in range (1,k+1):
    
    dict[i]=i*i
print(dict)

donner une valeur8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [29]:
def  missing_char(s,n):
    s=input("donner une chaine ")
    n=int(input("donner une valeur "))
    for n in range (0,len(s)+1):
        s=s.replace(s[n],'')
print(s)

50


In [30]:
import numpy as np  
array=np.random.randint(1,10, size=(3,2))
l=array.tolist()
print(array)
print(l)

[[6 1]
 [2 2]
 [8 2]]
[[6, 1], [2, 2], [8, 2]]


In [31]:
import numpy as np  
array=np.random.randint(1,10, size=(1,3))
array1=np.random.randint(1,10, size=(1,3))
np.cov(array,array1)
print(array)
print(array1)
print(np.cov(array,array1))

[[7 6 1]]
[[8 2 1]]
[[10.33333333  8.83333333]
 [ 8.83333333 14.33333333]]


In [20]:
from math import *
s=input("donner une chaine")
l=s.split(',')
for i in range (0,len(l)):
    l[i]=int(l[i])
for i in range (0,len(l)):
    l[i]=sqrt((l[i]*2*50)/30)
    print(round(l[i]),end=',')

donner une chaine50
13,